{% set name = "dm-haiku" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmind/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e9896d161938b53f869fde207f3f6fca496d09b2a47d21dd9b6b65e897ad6aab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - absl-py >=0.7.1
    - numpy >=1.18.0
    - python
    - jax

test:
  imports:
    - haiku
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/dm-haiku
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Haiku is a library for building neural networks in JAX.
  description: |
    Haiku is a simple neural network library for JAX developed by some 
    of the authors of Sonnet, a neural network library for TensorFlow.
  doc_url: https://github.com/deepmind/dm-haiku
  dev_url: https://dm-haiku.readthedocs.io/

extra:
  recipe-maintainers:
    - jan-janssen
